config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_ssh-agent.service:
    src: config/systemd/user/ssh-agent.service
    dst: ~/.config/systemd/user/ssh-agent.service
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  SHARED:
    dotfiles:
    - f_xinitrc
    - f_zshrc
    - f_zprofile
    - f_gitconfig
    - f_ssh-agent.service
    - d_i3
    - d_polybar
    - d_kitty
    - d_nvim
  SLL:
    include:
      - SHARED
  SLPC:
    include:
      - SHARED
